### ISSUE TITLE
Bug au niveau de l'IHM

### ISSUE THREAD

**Issue by visagey** [lespetitspedestres/EnGarde#10]
Lorsqu'on clique sur le bouton "Rejouer" qui s'affiche en fin de partie, la méthode `getPlayerName()` est appelée avec `null` :
```
Exception in thread "main" java.lang.NullPointerException
	at engine.Engine.getPlayerName(Engine.java:197)
	at gui.windows.WindowDeath.render(WindowDeath.java:61)
	at gui.scene.SceneGame.render(SceneGame.java:760)
	at gui.windows.MainPanel.paint(MainPanel.java:57)
	at gui.windows.MainFrame.update(MainFrame.java:285)
	at gui.windows.MainFrame.go(MainFrame.java:243)
	at gui.windows.MainFrame.<init>(MainFrame.java:209)
	at gui.windows.MainFrame.main(MainFrame.java:290)
```

Fait amusant, ça ne se produit pas avec le bouton "Nouvelle partie" du menu.

**Comment by MackValentine** [comment]
De ce que j'ai regardé, ça vient pas de chez moi, mais du côté du moteur :
Quand la fonction newGame() est appelé, la variable is_end_of_game n'est pas refresh, donc le menu de fin de jeu apparaît, alors qu'il n'y a aucun vainqueur.

**Comment by visagey** [comment]
Fait dans d3e5069a853632f20e8be3caf7b7739467f25a20.
